### ISSUE TITLE
Admin - impossible de centrer une image dans un article

### ISSUE THREAD

**Issue by MarieOphelie** [Youkoulayley/AveDeux#62]

**Comment by Youkoulayley** [comment]
Alors, si on peut par contre, y'a un petit trick je viens de voir.
J'ai trouvé deux solutions pour le faire : 

- Placer le curseur juste avant l'image, et la l'option "centrer" fonctionne
- Sélectionner l'image et cliquer sur l'icone qui supprime la mise en forme, pareil l'option centrer fonctionne.

Par contre c'est vrai que c'est pas dispo par défaut, je vais essayer de voir si je trouve quelque chose.

**Comment by MarieOphelie** [comment]
Ok ok. Je viens d'essayer, ta solution n°1 fonctionne et est assez simple, par contre la 2ème me supprime vraiment toute la mise en forme, c'est-à-dire que l'image retrouve sa taille d'origine et la bordure disparaît.
Vu qu'on sait le faire en plaçant le curseur avant l'image, ne te prends pas trop la tête pour trouver une autre solution. :)
