### ISSUE TITLE
Responsive - planning des sorties

### ISSUE THREAD

**Issue by MarieOphelie** [Youkoulayley/AveDeux#64]
Le mode "semaine" n'est pas très lisible au niveau des dates, qui se chevauchent

**Comment by Youkoulayley** [comment]
Je pense qu'il va falloir faire avec, parce que j'ai pas de solutions miracle ici :/
En mode responsive, je pense qu'il faudrait affiche qu'un mode jour, voir mois. Le problème du mode semaine c'est qu'il essaie d'afficher trop d'info sur une seule ligne, et je vais pas pouvoir changer ça c'est un module que j'utilise. Et je vois pas comment je peux faire ça :D

**Comment by MarieOphelie** [comment]
D'ac pas de souci, c'est vraiment un défaut mineur donc pas de problème :)
