### ISSUE TITLE
Responsive - lecture article

### ISSUE THREAD

**Issue by MarieOphelie** [Youkoulayley/AveDeux#65]
Le début du texte chevauche l'image de "couverture" de l'article

![1542789609-screenshot-2018-11-21-07-29-06](https://user-images.githubusercontent.com/19188496/48884663-be608f80-ee25-11e8-8022-27f5362209a2.png)

**Comment by MarieOphelie** [comment]
Après réflexion, je pense que ce bug n'en est pas tout à fait un. Le texte sur la couverture est plus ou moins normal, c'est le chapô que tu as configuré pour qu'il apparaisse comme ça je pense. Là, l'effet bug vient du fait qu'Elpio a mis un chapô hyper long dans son article ; sur les autres articles "normaux", l'effet rendu n'est pas du tout similaire.

**Comment by Youkoulayley** [comment]
A voir avec les vrais données du site, et avec l'utilisation. On réouvrira le bug si nécessaire.
