### ISSUE TITLE
Admin - tri de la liste des articles

### ISSUE THREAD

**Issue by MarieOphelie** [Youkoulayley/AveDeux#74]
1. J'ai eu du mal à comprendre qu'on pouvait trier les articles par titre, catégorie, date, etc. Serait-il possible de rajouter des [petites flèches de tri](https://image.freepik.com/icones-gratuites/fleches-de-tri-quelques-pointant-vers-le-haut-et-vers-le-bas_318-42272.jpg) à côté du titre de chaque colonne ?

2. Est-il aussi possible d'afficher par défaut les articles dans l'ordre déchronologique (plus récent au début, plus vieux à la fin), comme actuellement ?

**Comment by Youkoulayley** [comment]
Ce n'est plus le cas avec la nouvelle page d'index
