### ISSUE TITLE
Page d'accueil : problème longueur de la vignette selon la longueur du chapô

### ISSUE THREAD

**Issue by MarieOphelie** [Youkoulayley/AveDeux#76]
La vignette d'un article qui a un chapô immense s'allonge démesurément en page d'accueil, et allonge donc la vignette de l'article qui est à côté d'elle :

![chapo long](https://user-images.githubusercontent.com/19188496/48929822-60e34600-eeec-11e8-9290-87d4fbea54db.JPG)

Y a-t-il possibilité de limiter la longueur de la vignette ? (ou tout simplement de limiter le nombre de caractères autorisés dans le champ de rédaction du chapô ?)

**Comment by Youkoulayley** [comment]
Comme pour #65 les articles devraient être plus uniformisés sur la vraie version. On réouvrira si besoin.
