### ISSUE TITLE
Responsive - 2 intitulés à corriger sur page "Tous les articles"

### ISSUE THREAD

**Issue by MarieOphelie** [Youkoulayley/AveDeux#80]
1. Onglet Bilan : "Articles consacrés au bilan d'une saison ou **d'une série**" (et non pas "d'un épisode", car si c'est d'un épisode c'est plutôt une critique à mon sens).

![screenshot_2018-11-25-09-10-36](https://user-images.githubusercontent.com/19188496/48981775-3d7dee00-f0da-11e8-9079-ed3358a9318e.png)

2. Onglet Focus : "Articles consacrés à **l'**aspect particulier d'une série".

![screenshot_2018-11-25-09-11-10](https://user-images.githubusercontent.com/19188496/48981794-5d151680-f0da-11e8-988f-d350034d17cc.png)

**Comment by Youkoulayley** [comment]
Sera corrigé lors du prochain vidage de la base de données (quand je rapatrierai les données pour les denriers tests)
